# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'groupSpectrumDialog.ui'
#
# Created: Wed Feb  4 06:47:32 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupSpectrumDialog(object):
    def setupUi(self, GroupSpectrumDialog):
        GroupSpectrumDialog.setObjectName(_fromUtf8("GroupSpectrumDialog"))
        GroupSpectrumDialog.resize(870, 590)
        self.gridLayout = QtGui.QGridLayout(GroupSpectrumDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBoxConditions = QtGui.QGroupBox(GroupSpectrumDialog)
        self.groupBoxConditions.setObjectName(_fromUtf8("groupBoxConditions"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxConditions)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelFmin = QtGui.QLabel(self.groupBoxConditions)
        self.labelFmin.setObjectName(_fromUtf8("labelFmin"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelFmin)
        self.spinBoxFmin = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxFmin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFmin.setObjectName(_fromUtf8("spinBoxFmin"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxFmin)
        self.labelFmax = QtGui.QLabel(self.groupBoxConditions)
        self.labelFmax.setObjectName(_fromUtf8("labelFmax"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelFmax)
        self.spinBoxFmax = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxFmax.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFmax.setMaximum(150)
        self.spinBoxFmax.setProperty("value", 40)
        self.spinBoxFmax.setObjectName(_fromUtf8("spinBoxFmax"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxFmax)
        self.labelFormat = QtGui.QLabel(self.groupBoxConditions)
        self.labelFormat.setObjectName(_fromUtf8("labelFormat"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelFormat)
        self.comboBoxFormat = QtGui.QComboBox(self.groupBoxConditions)
        self.comboBoxFormat.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBoxFormat.setObjectName(_fromUtf8("comboBoxFormat"))
        self.comboBoxFormat.addItem(_fromUtf8(""))
        self.comboBoxFormat.addItem(_fromUtf8(""))
        self.comboBoxFormat.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBoxFormat)
        self.checkBoxGroupAverage = QtGui.QCheckBox(self.groupBoxConditions)
        self.checkBoxGroupAverage.setObjectName(_fromUtf8("checkBoxGroupAverage"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.SpanningRole, self.checkBoxGroupAverage)
        self.checkBox = QtGui.QCheckBox(self.groupBoxConditions)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.SpanningRole, self.checkBox)
        self.horizontalLayout_5.addLayout(self.formLayout_2)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.labelNfft = QtGui.QLabel(self.groupBoxConditions)
        self.labelNfft.setObjectName(_fromUtf8("labelNfft"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNfft)
        self.spinBoxNfft = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxNfft.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxNfft.setMaximum(10000)
        self.spinBoxNfft.setProperty("value", 2048)
        self.spinBoxNfft.setObjectName(_fromUtf8("spinBoxNfft"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxNfft)
        self.checkBoxLogarithm = QtGui.QCheckBox(self.groupBoxConditions)
        self.checkBoxLogarithm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxLogarithm.setAutoFillBackground(False)
        self.checkBoxLogarithm.setChecked(True)
        self.checkBoxLogarithm.setObjectName(_fromUtf8("checkBoxLogarithm"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.SpanningRole, self.checkBoxLogarithm)
        self.labelResolution = QtGui.QLabel(self.groupBoxConditions)
        self.labelResolution.setObjectName(_fromUtf8("labelResolution"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelResolution)
        self.spinBoxResolution = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxResolution.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxResolution.setMinimum(100)
        self.spinBoxResolution.setMaximum(1000)
        self.spinBoxResolution.setProperty("value", 600)
        self.spinBoxResolution.setObjectName(_fromUtf8("spinBoxResolution"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxResolution)
        self.checkBoxPlotChannels = QtGui.QCheckBox(self.groupBoxConditions)
        self.checkBoxPlotChannels.setObjectName(_fromUtf8("checkBoxPlotChannels"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.SpanningRole, self.checkBoxPlotChannels)
        self.horizontalLayout_5.addLayout(self.formLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelLayout = QtGui.QLabel(self.groupBoxConditions)
        self.labelLayout.setObjectName(_fromUtf8("labelLayout"))
        self.horizontalLayout_6.addWidget(self.labelLayout)
        self.lineEditLayout = QtGui.QLineEdit(self.groupBoxConditions)
        self.lineEditLayout.setObjectName(_fromUtf8("lineEditLayout"))
        self.horizontalLayout_6.addWidget(self.lineEditLayout)
        self.pushButtonBrowseLayout = QtGui.QPushButton(self.groupBoxConditions)
        self.pushButtonBrowseLayout.setObjectName(_fromUtf8("pushButtonBrowseLayout"))
        self.horizontalLayout_6.addWidget(self.pushButtonBrowseLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButtonSeriesFromTriggers = QtGui.QPushButton(self.groupBoxConditions)
        self.pushButtonSeriesFromTriggers.setObjectName(_fromUtf8("pushButtonSeriesFromTriggers"))
        self.horizontalLayout_4.addWidget(self.pushButtonSeriesFromTriggers)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButtonAddTimeSeries = QtGui.QPushButton(self.groupBoxConditions)
        self.pushButtonAddTimeSeries.setObjectName(_fromUtf8("pushButtonAddTimeSeries"))
        self.horizontalLayout_4.addWidget(self.pushButtonAddTimeSeries)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelDestPath = QtGui.QLabel(self.groupBoxConditions)
        self.labelDestPath.setObjectName(_fromUtf8("labelDestPath"))
        self.horizontalLayout_2.addWidget(self.labelDestPath)
        self.lineEditDestPath = QtGui.QLineEdit(self.groupBoxConditions)
        self.lineEditDestPath.setObjectName(_fromUtf8("lineEditDestPath"))
        self.horizontalLayout_2.addWidget(self.lineEditDestPath)
        self.pushButtonBrowseDest = QtGui.QPushButton(self.groupBoxConditions)
        self.pushButtonBrowseDest.setObjectName(_fromUtf8("pushButtonBrowseDest"))
        self.horizontalLayout_2.addWidget(self.pushButtonBrowseDest)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelPath = QtGui.QLabel(self.groupBoxConditions)
        self.labelPath.setObjectName(_fromUtf8("labelPath"))
        self.horizontalLayout_7.addWidget(self.labelPath)
        self.lineEditPath = QtGui.QLineEdit(self.groupBoxConditions)
        self.lineEditPath.setObjectName(_fromUtf8("lineEditPath"))
        self.horizontalLayout_7.addWidget(self.lineEditPath)
        self.pushButtonBrowsePath = QtGui.QPushButton(self.groupBoxConditions)
        self.pushButtonBrowsePath.setObjectName(_fromUtf8("pushButtonBrowsePath"))
        self.horizontalLayout_7.addWidget(self.pushButtonBrowsePath)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 8, 0, 1, 1)
        self.scrollAreaConditions = QtGui.QScrollArea(self.groupBoxConditions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(self.scrollAreaConditions.sizePolicy().hasHeightForWidth())
        self.scrollAreaConditions.setSizePolicy(sizePolicy)
        self.scrollAreaConditions.setMaximumSize(QtCore.QSize(16777215, 550))
        self.scrollAreaConditions.setWidgetResizable(True)
        self.scrollAreaConditions.setObjectName(_fromUtf8("scrollAreaConditions"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 824, 142))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayoutConditions = QtGui.QVBoxLayout()
        self.verticalLayoutConditions.setObjectName(_fromUtf8("verticalLayoutConditions"))
        self.verticalLayout.addLayout(self.verticalLayoutConditions)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.scrollAreaConditions.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollAreaConditions, 5, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBoxTriggers = QtGui.QCheckBox(self.groupBoxConditions)
        self.checkBoxTriggers.setObjectName(_fromUtf8("checkBoxTriggers"))
        self.horizontalLayout.addWidget(self.checkBoxTriggers)
        self.label = QtGui.QLabel(self.groupBoxConditions)
        self.label.setEnabled(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxStart = QtGui.QComboBox(self.groupBoxConditions)
        self.comboBoxStart.setEnabled(False)
        self.comboBoxStart.setObjectName(_fromUtf8("comboBoxStart"))
        self.horizontalLayout.addWidget(self.comboBoxStart)
        self.label_2 = QtGui.QLabel(self.groupBoxConditions)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBoxEnd = QtGui.QComboBox(self.groupBoxConditions)
        self.comboBoxEnd.setEnabled(False)
        self.comboBoxEnd.setObjectName(_fromUtf8("comboBoxEnd"))
        self.horizontalLayout.addWidget(self.comboBoxEnd)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxConditions, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(GroupSpectrumDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.NoButton)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(GroupSpectrumDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), GroupSpectrumDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), GroupSpectrumDialog.reject)
        QtCore.QObject.connect(self.checkBoxTriggers, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBoxStart.setEnabled)
        QtCore.QObject.connect(self.checkBoxTriggers, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBoxEnd.setEnabled)
        QtCore.QObject.connect(self.checkBoxTriggers, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label.setEnabled)
        QtCore.QObject.connect(self.checkBoxTriggers, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxTriggers, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pushButtonAddTimeSeries.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(GroupSpectrumDialog)
        GroupSpectrumDialog.setTabOrder(self.spinBoxFmin, self.spinBoxFmax)
        GroupSpectrumDialog.setTabOrder(self.spinBoxFmax, self.comboBoxFormat)
        GroupSpectrumDialog.setTabOrder(self.comboBoxFormat, self.spinBoxNfft)
        GroupSpectrumDialog.setTabOrder(self.spinBoxNfft, self.checkBoxLogarithm)
        GroupSpectrumDialog.setTabOrder(self.checkBoxLogarithm, self.spinBoxResolution)
        GroupSpectrumDialog.setTabOrder(self.spinBoxResolution, self.checkBoxPlotChannels)
        GroupSpectrumDialog.setTabOrder(self.checkBoxPlotChannels, self.checkBox)
        GroupSpectrumDialog.setTabOrder(self.checkBox, self.checkBoxGroupAverage)
        GroupSpectrumDialog.setTabOrder(self.checkBoxGroupAverage, self.lineEditLayout)
        GroupSpectrumDialog.setTabOrder(self.lineEditLayout, self.pushButtonBrowseLayout)
        GroupSpectrumDialog.setTabOrder(self.pushButtonBrowseLayout, self.lineEditPath)
        GroupSpectrumDialog.setTabOrder(self.lineEditPath, self.pushButtonBrowsePath)
        GroupSpectrumDialog.setTabOrder(self.pushButtonBrowsePath, self.lineEditDestPath)
        GroupSpectrumDialog.setTabOrder(self.lineEditDestPath, self.pushButtonBrowseDest)
        GroupSpectrumDialog.setTabOrder(self.pushButtonBrowseDest, self.checkBoxTriggers)
        GroupSpectrumDialog.setTabOrder(self.checkBoxTriggers, self.comboBoxStart)
        GroupSpectrumDialog.setTabOrder(self.comboBoxStart, self.comboBoxEnd)
        GroupSpectrumDialog.setTabOrder(self.comboBoxEnd, self.scrollAreaConditions)
        GroupSpectrumDialog.setTabOrder(self.scrollAreaConditions, self.pushButtonSeriesFromTriggers)
        GroupSpectrumDialog.setTabOrder(self.pushButtonSeriesFromTriggers, self.pushButtonAddTimeSeries)
        GroupSpectrumDialog.setTabOrder(self.pushButtonAddTimeSeries, self.buttonBox)

    def retranslateUi(self, GroupSpectrumDialog):
        GroupSpectrumDialog.setWindowTitle(_translate("GroupSpectrumDialog", "Power spectrum", None))
        self.groupBoxConditions.setTitle(_translate("GroupSpectrumDialog", "Conditions", None))
        self.labelFmin.setToolTip(_translate("GroupSpectrumDialog", "Set the lower limit for the frequencies.", None))
        self.labelFmin.setText(_translate("GroupSpectrumDialog", "Min frequency of interest:", None))
        self.spinBoxFmin.setToolTip(_translate("GroupSpectrumDialog", "Set the lower limit for the frequencies.", None))
        self.spinBoxFmin.setSuffix(_translate("GroupSpectrumDialog", "Hz", None))
        self.labelFmax.setToolTip(_translate("GroupSpectrumDialog", "Set the upper limit for the frequencies.", None))
        self.labelFmax.setText(_translate("GroupSpectrumDialog", "Max frequency of interest:", None))
        self.spinBoxFmax.setToolTip(_translate("GroupSpectrumDialog", "Set the upper limit for the frequencies.", None))
        self.spinBoxFmax.setSuffix(_translate("GroupSpectrumDialog", "Hz", None))
        self.labelFormat.setToolTip(_translate("GroupSpectrumDialog", "Select the format for the images.", None))
        self.labelFormat.setText(_translate("GroupSpectrumDialog", "Image format:", None))
        self.comboBoxFormat.setToolTip(_translate("GroupSpectrumDialog", "Select the format for the images.", None))
        self.comboBoxFormat.setItemText(0, _translate("GroupSpectrumDialog", "png", None))
        self.comboBoxFormat.setItemText(1, _translate("GroupSpectrumDialog", "svg", None))
        self.comboBoxFormat.setItemText(2, _translate("GroupSpectrumDialog", "pdf", None))
        self.checkBoxGroupAverage.setText(_translate("GroupSpectrumDialog", "Compute group averages for selected channels", None))
        self.checkBox.setText(_translate("GroupSpectrumDialog", "Write ASCII file from selected channels", None))
        self.labelNfft.setToolTip(_translate("GroupSpectrumDialog", "The length of the tapers ie. the windows. The smaller it is the smoother are the PSDs.", None))
        self.labelNfft.setText(_translate("GroupSpectrumDialog", "Length of the tapers (ie. the windows):", None))
        self.spinBoxNfft.setToolTip(_translate("GroupSpectrumDialog", "The length of the tapers ie. the windows. The smaller it is the smoother are the PSDs.", None))
        self.checkBoxLogarithm.setToolTip(_translate("GroupSpectrumDialog", "Use logarithmic scale.", None))
        self.checkBoxLogarithm.setText(_translate("GroupSpectrumDialog", "Use logarithmic scale", None))
        self.labelResolution.setToolTip(_translate("GroupSpectrumDialog", "The resolution in dots per inch.", None))
        self.labelResolution.setText(_translate("GroupSpectrumDialog", "Resolution:", None))
        self.spinBoxResolution.setToolTip(_translate("GroupSpectrumDialog", "The resolution in dots per inch.", None))
        self.spinBoxResolution.setSuffix(_translate("GroupSpectrumDialog", "dpi", None))
        self.checkBoxPlotChannels.setToolTip(_translate("GroupSpectrumDialog", "If checked, power spectrum densities of channels on the list are saved in files individually.", None))
        self.checkBoxPlotChannels.setText(_translate("GroupSpectrumDialog", "Plot individual channels", None))
        self.labelLayout.setText(_translate("GroupSpectrumDialog", "Select a layout file:", None))
        self.lineEditLayout.setToolTip(_translate("GroupSpectrumDialog", "Select a layout file.", None))
        self.pushButtonBrowseLayout.setToolTip(_translate("GroupSpectrumDialog", "Select a layout file.", None))
        self.pushButtonBrowseLayout.setText(_translate("GroupSpectrumDialog", "Browse...", None))
        self.pushButtonSeriesFromTriggers.setText(_translate("GroupSpectrumDialog", "Construct time series from triggers", None))
        self.pushButtonAddTimeSeries.setToolTip(_translate("GroupSpectrumDialog", "Add condition.", None))
        self.pushButtonAddTimeSeries.setText(_translate("GroupSpectrumDialog", "Add time series", None))
        self.labelDestPath.setToolTip(_translate("GroupSpectrumDialog", "Select a destination path for the images.", None))
        self.labelDestPath.setText(_translate("GroupSpectrumDialog", "Select a destination path:", None))
        self.lineEditDestPath.setToolTip(_translate("GroupSpectrumDialog", "Select a destination path for the images and ASCII files.", None))
        self.pushButtonBrowseDest.setText(_translate("GroupSpectrumDialog", "Browse...", None))
        self.labelPath.setToolTip(_translate("GroupSpectrumDialog", "Select a path to read the files from. Make sure all the files end with \'.fif\'.", None))
        self.labelPath.setText(_translate("GroupSpectrumDialog", "Select a path to read the files from:", None))
        self.lineEditPath.setToolTip(_translate("GroupSpectrumDialog", "Select a path to read the files from. Make sure all the files end with \'.fif\'.", None))
        self.pushButtonBrowsePath.setToolTip(_translate("GroupSpectrumDialog", "Select a path for the files to use.", None))
        self.pushButtonBrowsePath.setText(_translate("GroupSpectrumDialog", "Browse...", None))
        self.checkBoxTriggers.setText(_translate("GroupSpectrumDialog", "Use triggers for time series", None))
        self.label.setText(_translate("GroupSpectrumDialog", "Start trigger:", None))
        self.label_2.setText(_translate("GroupSpectrumDialog", "End trigger:", None))

