# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Mar 19 02:59:18 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(856, 942)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelRaw = QtGui.QLabel(self.centralwidget)
        self.labelRaw.setObjectName(_fromUtf8("labelRaw"))
        self.horizontalLayout_2.addWidget(self.labelRaw)
        self.pushButtonFileInfo = QtGui.QPushButton(self.centralwidget)
        self.pushButtonFileInfo.setObjectName(_fromUtf8("pushButtonFileInfo"))
        self.horizontalLayout_2.addWidget(self.pushButtonFileInfo)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.tabWidget = QtGui.QTabWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPreProcess = QtGui.QWidget()
        self.tabPreProcess.setObjectName(_fromUtf8("tabPreProcess"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabPreProcess)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.tabPreProcess)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 798, 675))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(741, 675))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonCalculateSSP = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonCalculateSSP.setObjectName(_fromUtf8("pushButtonCalculateSSP"))
        self.gridLayout_2.addWidget(self.pushButtonCalculateSSP, 1, 0, 1, 1)
        self.pushButtonSave = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonSave.setEnabled(False)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.gridLayout_2.addWidget(self.pushButtonSave, 2, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget_2 = QtGui.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayoutFilter = QtGui.QFormLayout()
        self.formLayoutFilter.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutFilter.setObjectName(_fromUtf8("formLayoutFilter"))
        self.labelHighCutOff = QtGui.QLabel(self.layoutWidget_2)
        self.labelHighCutOff.setObjectName(_fromUtf8("labelHighCutOff"))
        self.formLayoutFilter.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelHighCutOff)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.doubleSpinBoxHighCutOff = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxHighCutOff.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxHighCutOff.setSizePolicy(sizePolicy)
        self.doubleSpinBoxHighCutOff.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxHighCutOff.setMaximum(500.0)
        self.doubleSpinBoxHighCutOff.setProperty("value", 80.0)
        self.doubleSpinBoxHighCutOff.setObjectName(_fromUtf8("doubleSpinBoxHighCutOff"))
        self.horizontalLayout_10.addWidget(self.doubleSpinBoxHighCutOff)
        self.checkBoxHighCutOff = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBoxHighCutOff.setText(_fromUtf8(""))
        self.checkBoxHighCutOff.setChecked(True)
        self.checkBoxHighCutOff.setObjectName(_fromUtf8("checkBoxHighCutOff"))
        self.horizontalLayout_10.addWidget(self.checkBoxHighCutOff)
        self.formLayoutFilter.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.labelNotchFilter = QtGui.QLabel(self.layoutWidget_2)
        self.labelNotchFilter.setObjectName(_fromUtf8("labelNotchFilter"))
        self.formLayoutFilter.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelNotchFilter)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.doubleSpinBoxNotchFilter = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxNotchFilter.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxNotchFilter.setSizePolicy(sizePolicy)
        self.doubleSpinBoxNotchFilter.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxNotchFilter.setMaximum(200.0)
        self.doubleSpinBoxNotchFilter.setProperty("value", 50.0)
        self.doubleSpinBoxNotchFilter.setObjectName(_fromUtf8("doubleSpinBoxNotchFilter"))
        self.horizontalLayout_9.addWidget(self.doubleSpinBoxNotchFilter)
        self.checkBoxNotch = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBoxNotch.setText(_fromUtf8(""))
        self.checkBoxNotch.setChecked(True)
        self.checkBoxNotch.setObjectName(_fromUtf8("checkBoxNotch"))
        self.horizontalLayout_9.addWidget(self.checkBoxNotch)
        self.formLayoutFilter.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.pushButtonFilter = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFilter.sizePolicy().hasHeightForWidth())
        self.pushButtonFilter.setSizePolicy(sizePolicy)
        self.pushButtonFilter.setObjectName(_fromUtf8("pushButtonFilter"))
        self.formLayoutFilter.setWidget(3, QtGui.QFormLayout.FieldRole, self.pushButtonFilter)
        self.labelLowCutOff = QtGui.QLabel(self.layoutWidget_2)
        self.labelLowCutOff.setObjectName(_fromUtf8("labelLowCutOff"))
        self.formLayoutFilter.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelLowCutOff)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.doubleSpinBoxLowCutOff = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBoxLowCutOff.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxLowCutOff.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxLowCutOff.setSizePolicy(sizePolicy)
        self.doubleSpinBoxLowCutOff.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxLowCutOff.setMaximum(100.0)
        self.doubleSpinBoxLowCutOff.setProperty("value", 5.0)
        self.doubleSpinBoxLowCutOff.setObjectName(_fromUtf8("doubleSpinBoxLowCutOff"))
        self.horizontalLayout_11.addWidget(self.doubleSpinBoxLowCutOff)
        self.checkBoxLowCutOff = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBoxLowCutOff.setText(_fromUtf8(""))
        self.checkBoxLowCutOff.setObjectName(_fromUtf8("checkBoxLowCutOff"))
        self.horizontalLayout_11.addWidget(self.checkBoxLowCutOff)
        self.formLayoutFilter.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.verticalLayout_2.addLayout(self.formLayoutFilter)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.line_2 = QtGui.QFrame(self.layoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.labelBads = QtGui.QLabel(self.layoutWidget_2)
        self.labelBads.setObjectName(_fromUtf8("labelBads"))
        self.verticalLayout_2.addWidget(self.labelBads)
        self.listWidgetBads = QtGui.QListWidget(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetBads.sizePolicy().hasHeightForWidth())
        self.listWidgetBads.setSizePolicy(sizePolicy)
        self.listWidgetBads.setMaximumSize(QtCore.QSize(16777215, 50))
        self.listWidgetBads.setFlow(QtGui.QListView.LeftToRight)
        self.listWidgetBads.setObjectName(_fromUtf8("listWidgetBads"))
        self.verticalLayout_2.addWidget(self.listWidgetBads)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonAddBads = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonAddBads.setObjectName(_fromUtf8("pushButtonAddBads"))
        self.horizontalLayout.addWidget(self.pushButtonAddBads)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.line = QtGui.QFrame(self.layoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelEventID = QtGui.QLabel(self.layoutWidget_2)
        self.labelEventID.setObjectName(_fromUtf8("labelEventID"))
        self.horizontalLayout_7.addWidget(self.labelEventID)
        self.labelBlinkId = QtGui.QLabel(self.layoutWidget_2)
        self.labelBlinkId.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelBlinkId.setObjectName(_fromUtf8("labelBlinkId"))
        self.horizontalLayout_7.addWidget(self.labelBlinkId)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelChannel = QtGui.QLabel(self.layoutWidget_2)
        self.labelChannel.setObjectName(_fromUtf8("labelChannel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelChannel)
        self.comboBoxChannelSelect = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBoxChannelSelect.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBoxChannelSelect.setObjectName(_fromUtf8("comboBoxChannelSelect"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxChannelSelect)
        self.doubleSpinBoxLowPass = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBoxLowPass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxLowPass.setProperty("value", 1.0)
        self.doubleSpinBoxLowPass.setObjectName(_fromUtf8("doubleSpinBoxLowPass"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxLowPass)
        self.labelLowPass = QtGui.QLabel(self.layoutWidget_2)
        self.labelLowPass.setObjectName(_fromUtf8("labelLowPass"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelLowPass)
        self.labelHighPass = QtGui.QLabel(self.layoutWidget_2)
        self.labelHighPass.setObjectName(_fromUtf8("labelHighPass"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelHighPass)
        self.doubleSpinBoxHighPass = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBoxHighPass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxHighPass.setSingleStep(1.0)
        self.doubleSpinBoxHighPass.setProperty("value", 10.0)
        self.doubleSpinBoxHighPass.setObjectName(_fromUtf8("doubleSpinBoxHighPass"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxHighPass)
        self.labelFilterLength = QtGui.QLabel(self.layoutWidget_2)
        self.labelFilterLength.setObjectName(_fromUtf8("labelFilterLength"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelFilterLength)
        self.spinBoxFilterLength = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinBoxFilterLength.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFilterLength.setProperty("value", 10)
        self.spinBoxFilterLength.setObjectName(_fromUtf8("spinBoxFilterLength"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.spinBoxFilterLength)
        self.labelStart = QtGui.QLabel(self.layoutWidget_2)
        self.labelStart.setObjectName(_fromUtf8("labelStart"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelStart)
        self.doubleSpinBoxStart = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBoxStart.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxStart.setProperty("value", 5.0)
        self.doubleSpinBoxStart.setObjectName(_fromUtf8("doubleSpinBoxStart"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxStart)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.pushButtonFindEogEvents = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFindEogEvents.sizePolicy().hasHeightForWidth())
        self.pushButtonFindEogEvents.setSizePolicy(sizePolicy)
        self.pushButtonFindEogEvents.setObjectName(_fromUtf8("pushButtonFindEogEvents"))
        self.verticalLayout_2.addWidget(self.pushButtonFindEogEvents)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.layoutWidget_3 = QtGui.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableWidgetEvents = QtGui.QTableWidget(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetEvents.sizePolicy().hasHeightForWidth())
        self.tableWidgetEvents.setSizePolicy(sizePolicy)
        self.tableWidgetEvents.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetEvents.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetEvents.setObjectName(_fromUtf8("tableWidgetEvents"))
        self.tableWidgetEvents.setColumnCount(0)
        self.tableWidgetEvents.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidgetEvents)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButtonDelete = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonDelete.setEnabled(False)
        self.pushButtonDelete.setObjectName(_fromUtf8("pushButtonDelete"))
        self.horizontalLayout_8.addWidget(self.pushButtonDelete)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPreProcess, _fromUtf8(""))
        self.tabSpectrum = QtGui.QWidget()
        self.tabSpectrum.setObjectName(_fromUtf8("tabSpectrum"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabSpectrum)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pushButtonPlot = QtGui.QPushButton(self.tabSpectrum)
        self.pushButtonPlot.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButtonPlot.setObjectName(_fromUtf8("pushButtonPlot"))
        self.horizontalLayout_3.addWidget(self.pushButtonPlot)
        self.pushButtonGroupPlot = QtGui.QPushButton(self.tabSpectrum)
        self.pushButtonGroupPlot.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButtonGroupPlot.setObjectName(_fromUtf8("pushButtonGroupPlot"))
        self.horizontalLayout_3.addWidget(self.pushButtonGroupPlot)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.groupBoxConditions = QtGui.QGroupBox(self.tabSpectrum)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.groupBoxConditions.sizePolicy().hasHeightForWidth())
        self.groupBoxConditions.setSizePolicy(sizePolicy)
        self.groupBoxConditions.setObjectName(_fromUtf8("groupBoxConditions"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxConditions)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelFmin = QtGui.QLabel(self.groupBoxConditions)
        self.labelFmin.setObjectName(_fromUtf8("labelFmin"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelFmin)
        self.spinBoxFmin = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxFmin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFmin.setObjectName(_fromUtf8("spinBoxFmin"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxFmin)
        self.labelFmax = QtGui.QLabel(self.groupBoxConditions)
        self.labelFmax.setObjectName(_fromUtf8("labelFmax"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelFmax)
        self.spinBoxFmax = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxFmax.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFmax.setMaximum(150)
        self.spinBoxFmax.setProperty("value", 40)
        self.spinBoxFmax.setObjectName(_fromUtf8("spinBoxFmax"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxFmax)
        self.horizontalLayout_5.addLayout(self.formLayout_2)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.labelNfft = QtGui.QLabel(self.groupBoxConditions)
        self.labelNfft.setObjectName(_fromUtf8("labelNfft"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNfft)
        self.spinBoxNfft = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxNfft.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxNfft.setMaximum(10000)
        self.spinBoxNfft.setProperty("value", 2048)
        self.spinBoxNfft.setObjectName(_fromUtf8("spinBoxNfft"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxNfft)
        self.checkBoxLogarithm = QtGui.QCheckBox(self.groupBoxConditions)
        self.checkBoxLogarithm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxLogarithm.setAutoFillBackground(False)
        self.checkBoxLogarithm.setChecked(True)
        self.checkBoxLogarithm.setObjectName(_fromUtf8("checkBoxLogarithm"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.SpanningRole, self.checkBoxLogarithm)
        self.horizontalLayout_5.addLayout(self.formLayout_6)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButtonSeriesFromTriggers = QtGui.QPushButton(self.groupBoxConditions)
        self.pushButtonSeriesFromTriggers.setObjectName(_fromUtf8("pushButtonSeriesFromTriggers"))
        self.horizontalLayout_4.addWidget(self.pushButtonSeriesFromTriggers)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.pushButtonAddTimeSeries = QtGui.QPushButton(self.groupBoxConditions)
        self.pushButtonAddTimeSeries.setObjectName(_fromUtf8("pushButtonAddTimeSeries"))
        self.horizontalLayout_4.addWidget(self.pushButtonAddTimeSeries)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelLayout = QtGui.QLabel(self.groupBoxConditions)
        self.labelLayout.setObjectName(_fromUtf8("labelLayout"))
        self.horizontalLayout_6.addWidget(self.labelLayout)
        self.lineEditLayout = QtGui.QLineEdit(self.groupBoxConditions)
        self.lineEditLayout.setObjectName(_fromUtf8("lineEditLayout"))
        self.horizontalLayout_6.addWidget(self.lineEditLayout)
        self.pushButtonBrowseLayout = QtGui.QPushButton(self.groupBoxConditions)
        self.pushButtonBrowseLayout.setObjectName(_fromUtf8("pushButtonBrowseLayout"))
        self.horizontalLayout_6.addWidget(self.pushButtonBrowseLayout)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.scrollAreaConditions = QtGui.QScrollArea(self.groupBoxConditions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(self.scrollAreaConditions.sizePolicy().hasHeightForWidth())
        self.scrollAreaConditions.setSizePolicy(sizePolicy)
        self.scrollAreaConditions.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaConditions.setMaximumSize(QtCore.QSize(16777215, 550))
        self.scrollAreaConditions.setBaseSize(QtCore.QSize(0, 0))
        self.scrollAreaConditions.setWidgetResizable(True)
        self.scrollAreaConditions.setObjectName(_fromUtf8("scrollAreaConditions"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 788, 437))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayoutConditions = QtGui.QVBoxLayout()
        self.verticalLayoutConditions.setObjectName(_fromUtf8("verticalLayoutConditions"))
        self.gridLayout_6.addLayout(self.verticalLayoutConditions, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 1, 0, 1, 1)
        self.scrollAreaConditions.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollAreaConditions, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxConditions, 1, 0, 2, 1)
        self.tabWidget.addTab(self.tabSpectrum, _fromUtf8(""))
        self.textEdit = QtGui.QTextEdit(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.progressBar = QtGui.QProgressBar(self.splitter_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.splitter_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionDirectOutput = QtGui.QAction(MainWindow)
        self.actionDirectOutput.setCheckable(True)
        self.actionDirectOutput.setChecked(True)
        self.actionDirectOutput.setObjectName(_fromUtf8("actionDirectOutput"))
        self.menuFile.addAction(self.actionDirectOutput)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkBoxNotch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxNotchFilter.setEnabled)
        QtCore.QObject.connect(self.checkBoxHighCutOff, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxHighCutOff.setEnabled)
        QtCore.QObject.connect(self.checkBoxLowCutOff, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxLowCutOff.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonFileInfo, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.doubleSpinBoxLowCutOff)
        MainWindow.setTabOrder(self.doubleSpinBoxLowCutOff, self.checkBoxLowCutOff)
        MainWindow.setTabOrder(self.checkBoxLowCutOff, self.doubleSpinBoxHighCutOff)
        MainWindow.setTabOrder(self.doubleSpinBoxHighCutOff, self.checkBoxHighCutOff)
        MainWindow.setTabOrder(self.checkBoxHighCutOff, self.doubleSpinBoxNotchFilter)
        MainWindow.setTabOrder(self.doubleSpinBoxNotchFilter, self.checkBoxNotch)
        MainWindow.setTabOrder(self.checkBoxNotch, self.pushButtonFilter)
        MainWindow.setTabOrder(self.pushButtonFilter, self.listWidgetBads)
        MainWindow.setTabOrder(self.listWidgetBads, self.pushButtonAddBads)
        MainWindow.setTabOrder(self.pushButtonAddBads, self.comboBoxChannelSelect)
        MainWindow.setTabOrder(self.comboBoxChannelSelect, self.doubleSpinBoxLowPass)
        MainWindow.setTabOrder(self.doubleSpinBoxLowPass, self.doubleSpinBoxHighPass)
        MainWindow.setTabOrder(self.doubleSpinBoxHighPass, self.spinBoxFilterLength)
        MainWindow.setTabOrder(self.spinBoxFilterLength, self.doubleSpinBoxStart)
        MainWindow.setTabOrder(self.doubleSpinBoxStart, self.pushButtonFindEogEvents)
        MainWindow.setTabOrder(self.pushButtonFindEogEvents, self.tableWidgetEvents)
        MainWindow.setTabOrder(self.tableWidgetEvents, self.pushButtonDelete)
        MainWindow.setTabOrder(self.pushButtonDelete, self.pushButtonCalculateSSP)
        MainWindow.setTabOrder(self.pushButtonCalculateSSP, self.pushButtonSave)
        MainWindow.setTabOrder(self.pushButtonSave, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.spinBoxFmin)
        MainWindow.setTabOrder(self.spinBoxFmin, self.spinBoxNfft)
        MainWindow.setTabOrder(self.spinBoxNfft, self.spinBoxFmax)
        MainWindow.setTabOrder(self.spinBoxFmax, self.checkBoxLogarithm)
        MainWindow.setTabOrder(self.checkBoxLogarithm, self.lineEditLayout)
        MainWindow.setTabOrder(self.lineEditLayout, self.pushButtonBrowseLayout)
        MainWindow.setTabOrder(self.pushButtonBrowseLayout, self.scrollAreaConditions)
        MainWindow.setTabOrder(self.scrollAreaConditions, self.pushButtonSeriesFromTriggers)
        MainWindow.setTabOrder(self.pushButtonSeriesFromTriggers, self.pushButtonAddTimeSeries)
        MainWindow.setTabOrder(self.pushButtonAddTimeSeries, self.pushButtonPlot)
        MainWindow.setTabOrder(self.pushButtonPlot, self.pushButtonGroupPlot)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelRaw.setText(_translate("MainWindow", "No file selected!", None))
        self.pushButtonFileInfo.setText(_translate("MainWindow", "Show file info", None))
        self.pushButtonCalculateSSP.setToolTip(_translate("MainWindow", "Calculates SSP projection vectors using the events in the list above.", None))
        self.pushButtonCalculateSSP.setText(_translate("MainWindow", "Calculate SSP projections...", None))
        self.pushButtonSave.setText(_translate("MainWindow", "Save to file...", None))
        self.labelHighCutOff.setText(_translate("MainWindow", "High cut-off frequency:", None))
        self.doubleSpinBoxHighCutOff.setSuffix(_translate("MainWindow", "Hz", None))
        self.labelNotchFilter.setText(_translate("MainWindow", "Notch filtering:", None))
        self.doubleSpinBoxNotchFilter.setSuffix(_translate("MainWindow", "Hz", None))
        self.pushButtonFilter.setToolTip(_translate("MainWindow", "Start filtering.", None))
        self.pushButtonFilter.setText(_translate("MainWindow", "Filter!", None))
        self.labelLowCutOff.setText(_translate("MainWindow", "Low cut-off frequency:", None))
        self.doubleSpinBoxLowCutOff.setSuffix(_translate("MainWindow", "Hz", None))
        self.labelBads.setText(_translate("MainWindow", "Bad channels:", None))
        self.listWidgetBads.setToolTip(_translate("MainWindow", "Displays the selected bad channels.", None))
        self.pushButtonAddBads.setText(_translate("MainWindow", "Add...", None))
        self.labelEventID.setToolTip(_translate("MainWindow", "The index to assign to found events.", None))
        self.labelEventID.setText(_translate("MainWindow", "Event ID for blinks:", None))
        self.labelBlinkId.setText(_translate("MainWindow", "998", None))
        self.labelChannel.setToolTip(_translate("MainWindow", "Select specified channel for finding EOG artefacts. Preferably a channel with clear blinks.", None))
        self.labelChannel.setText(_translate("MainWindow", "Event channel:", None))
        self.comboBoxChannelSelect.setToolTip(_translate("MainWindow", "Select specified channel for finding EOG artefacts. Preferably a channel with clear blinks.", None))
        self.doubleSpinBoxLowPass.setToolTip(_translate("MainWindow", "Low pass filter frequency.", None))
        self.doubleSpinBoxLowPass.setSuffix(_translate("MainWindow", "Hz", None))
        self.labelLowPass.setToolTip(_translate("MainWindow", "Low pass filter frequency.", None))
        self.labelLowPass.setText(_translate("MainWindow", "Low pass:", None))
        self.labelHighPass.setToolTip(_translate("MainWindow", "High pass filter frequency.", None))
        self.labelHighPass.setText(_translate("MainWindow", "High pass:", None))
        self.doubleSpinBoxHighPass.setToolTip(_translate("MainWindow", "High pass filter frequency.", None))
        self.doubleSpinBoxHighPass.setSuffix(_translate("MainWindow", "Hz", None))
        self.labelFilterLength.setToolTip(_translate("MainWindow", "Sets the number of taps used for filtering.", None))
        self.labelFilterLength.setText(_translate("MainWindow", "Filter length:", None))
        self.spinBoxFilterLength.setToolTip(_translate("MainWindow", "Sets the number of taps used for filtering.", None))
        self.spinBoxFilterLength.setSuffix(_translate("MainWindow", "s", None))
        self.labelStart.setToolTip(_translate("MainWindow", "Set starting time for blink detection.", None))
        self.labelStart.setText(_translate("MainWindow", "Start time:", None))
        self.doubleSpinBoxStart.setToolTip(_translate("MainWindow", "Set starting time for blink detection.", None))
        self.doubleSpinBoxStart.setSuffix(_translate("MainWindow", "s", None))
        self.pushButtonFindEogEvents.setToolTip(_translate("MainWindow", "Start blink detection. The previous event list will be deleted!", None))
        self.pushButtonFindEogEvents.setText(_translate("MainWindow", "Find EOG events", None))
        self.tableWidgetEvents.setToolTip(_translate("MainWindow", "Found events.", None))
        self.pushButtonDelete.setToolTip(_translate("MainWindow", "Delete single event.", None))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete event", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPreProcess), _translate("MainWindow", "PreProcessing", None))
        self.pushButtonPlot.setToolTip(_translate("MainWindow", "Plot power spectrum.", None))
        self.pushButtonPlot.setText(_translate("MainWindow", "Plot power spectrum", None))
        self.pushButtonGroupPlot.setToolTip(_translate("MainWindow", "Plot several files and save them to a file.", None))
        self.pushButtonGroupPlot.setText(_translate("MainWindow", "Group plotting for several files...", None))
        self.groupBoxConditions.setTitle(_translate("MainWindow", "Conditions", None))
        self.labelFmin.setToolTip(_translate("MainWindow", "Set the lower limit for the frequencies.", None))
        self.labelFmin.setText(_translate("MainWindow", "Min frequency of interest:", None))
        self.spinBoxFmin.setToolTip(_translate("MainWindow", "Set the lower limit for the frequencies.", None))
        self.spinBoxFmin.setSuffix(_translate("MainWindow", "Hz", None))
        self.labelFmax.setToolTip(_translate("MainWindow", "Set the upper limit for the frequencies.", None))
        self.labelFmax.setText(_translate("MainWindow", "Max frequency of interest:", None))
        self.spinBoxFmax.setToolTip(_translate("MainWindow", "Set the upper limit for the frequencies.", None))
        self.spinBoxFmax.setSuffix(_translate("MainWindow", "Hz", None))
        self.labelNfft.setToolTip(_translate("MainWindow", "The length of the tapers ie. the windows. The smaller it is the smoother are the PSDs.", None))
        self.labelNfft.setText(_translate("MainWindow", "Length of the tapers (ie. the windows):", None))
        self.spinBoxNfft.setToolTip(_translate("MainWindow", "The length of the tapers ie. the windows. The smaller it is the smoother are the PSDs.", None))
        self.checkBoxLogarithm.setToolTip(_translate("MainWindow", "Use logarithmic scale.", None))
        self.checkBoxLogarithm.setText(_translate("MainWindow", "Use logarithmic scale", None))
        self.pushButtonSeriesFromTriggers.setToolTip(_translate("MainWindow", "Add a set of time series by reading events from the file. Each trigger may be used for defining a limit for an individual time series.", None))
        self.pushButtonSeriesFromTriggers.setText(_translate("MainWindow", "Construct time series from triggers...", None))
        self.pushButtonAddTimeSeries.setToolTip(_translate("MainWindow", "Add condition.", None))
        self.pushButtonAddTimeSeries.setText(_translate("MainWindow", "Add time series", None))
        self.labelLayout.setText(_translate("MainWindow", "Select a layout file:", None))
        self.lineEditLayout.setToolTip(_translate("MainWindow", "Select a layout file.", None))
        self.pushButtonBrowseLayout.setToolTip(_translate("MainWindow", "Select a layout file.", None))
        self.pushButtonBrowseLayout.setText(_translate("MainWindow", "Browse...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpectrum), _translate("MainWindow", "Power Spectrum", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionOpen.setText(_translate("MainWindow", "Open...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionDirectOutput.setText(_translate("MainWindow", "Direct output to console", None))

