# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectionDialog.ui'
#
# Created: Thu Mar 12 07:24:05 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProjectionDialog(object):
    def setupUi(self, ProjectionDialog):
        ProjectionDialog.setObjectName(_fromUtf8("ProjectionDialog"))
        ProjectionDialog.resize(783, 396)
        self.gridLayout = QtGui.QGridLayout(ProjectionDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonClose = QtGui.QPushButton(ProjectionDialog)
        self.pushButtonClose.setObjectName(_fromUtf8("pushButtonClose"))
        self.horizontalLayout.addWidget(self.pushButtonClose)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 2, 1, 1)
        self.splitter = QtGui.QSplitter(ProjectionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget_3 = QtGui.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelUsingEvents = QtGui.QLabel(self.layoutWidget_3)
        self.labelUsingEvents.setObjectName(_fromUtf8("labelUsingEvents"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelUsingEvents)
        self.labelStart = QtGui.QLabel(self.layoutWidget_3)
        self.labelStart.setObjectName(_fromUtf8("labelStart"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelStart)
        self.doubleSpinBoxStart = QtGui.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBoxStart.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxStart.setMinimum(-2.0)
        self.doubleSpinBoxStart.setMaximum(0.0)
        self.doubleSpinBoxStart.setSingleStep(0.1)
        self.doubleSpinBoxStart.setProperty("value", -0.2)
        self.doubleSpinBoxStart.setObjectName(_fromUtf8("doubleSpinBoxStart"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxStart)
        self.labelEnd = QtGui.QLabel(self.layoutWidget_3)
        self.labelEnd.setObjectName(_fromUtf8("labelEnd"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelEnd)
        self.doubleSpinBoxEnd = QtGui.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBoxEnd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxEnd.setMaximum(5.0)
        self.doubleSpinBoxEnd.setSingleStep(0.1)
        self.doubleSpinBoxEnd.setProperty("value", 0.2)
        self.doubleSpinBoxEnd.setObjectName(_fromUtf8("doubleSpinBoxEnd"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxEnd)
        self.pushButtonPlotEpochs = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlotEpochs.sizePolicy().hasHeightForWidth())
        self.pushButtonPlotEpochs.setSizePolicy(sizePolicy)
        self.pushButtonPlotEpochs.setObjectName(_fromUtf8("pushButtonPlotEpochs"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.pushButtonPlotEpochs)
        self.labelVectors = QtGui.QLabel(self.layoutWidget_3)
        self.labelVectors.setObjectName(_fromUtf8("labelVectors"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelVectors)
        self.spinBoxVectors = QtGui.QSpinBox(self.layoutWidget_3)
        self.spinBoxVectors.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxVectors.setMinimum(1)
        self.spinBoxVectors.setProperty("value", 2)
        self.spinBoxVectors.setObjectName(_fromUtf8("spinBoxVectors"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.spinBoxVectors)
        self.pushButtonShowEvents = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonShowEvents.setObjectName(_fromUtf8("pushButtonShowEvents"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.pushButtonShowEvents)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.line = QtGui.QFrame(self.layoutWidget_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_5.addWidget(self.line)
        self.labelProjections = QtGui.QLabel(self.layoutWidget_3)
        self.labelProjections.setObjectName(_fromUtf8("labelProjections"))
        self.verticalLayout_5.addWidget(self.labelProjections)
        self.listWidgetProjs = QtGui.QListWidget(self.layoutWidget_3)
        self.listWidgetProjs.setObjectName(_fromUtf8("listWidgetProjs"))
        self.verticalLayout_5.addWidget(self.listWidgetProjs)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonDelProj = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonDelProj.setEnabled(False)
        self.pushButtonDelProj.setObjectName(_fromUtf8("pushButtonDelProj"))
        self.horizontalLayout_2.addWidget(self.pushButtonDelProj)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonAddProj = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonAddProj.setObjectName(_fromUtf8("pushButtonAddProj"))
        self.horizontalLayout_2.addWidget(self.pushButtonAddProj)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.layoutWidget_4 = QtGui.QWidget(self.splitter)
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.labelEvents = QtGui.QLabel(self.layoutWidget_4)
        self.labelEvents.setObjectName(_fromUtf8("labelEvents"))
        self.verticalLayout_7.addWidget(self.labelEvents)
        self.tableWidgetEvents = QtGui.QTableWidget(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetEvents.sizePolicy().hasHeightForWidth())
        self.tableWidgetEvents.setSizePolicy(sizePolicy)
        self.tableWidgetEvents.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetEvents.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetEvents.setObjectName(_fromUtf8("tableWidgetEvents"))
        self.tableWidgetEvents.setColumnCount(1)
        self.tableWidgetEvents.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEvents.setHorizontalHeaderItem(0, item)
        self.verticalLayout_7.addWidget(self.tableWidgetEvents)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButtonDelEvent = QtGui.QPushButton(self.layoutWidget_4)
        self.pushButtonDelEvent.setEnabled(False)
        self.pushButtonDelEvent.setObjectName(_fromUtf8("pushButtonDelEvent"))
        self.horizontalLayout_10.addWidget(self.pushButtonDelEvent)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.gridLayout.addWidget(self.splitter, 2, 2, 1, 1)

        self.retranslateUi(ProjectionDialog)
        QtCore.QMetaObject.connectSlotsByName(ProjectionDialog)
        ProjectionDialog.setTabOrder(self.doubleSpinBoxStart, self.doubleSpinBoxEnd)
        ProjectionDialog.setTabOrder(self.doubleSpinBoxEnd, self.pushButtonPlotEpochs)
        ProjectionDialog.setTabOrder(self.pushButtonPlotEpochs, self.pushButtonShowEvents)
        ProjectionDialog.setTabOrder(self.pushButtonShowEvents, self.spinBoxVectors)
        ProjectionDialog.setTabOrder(self.spinBoxVectors, self.listWidgetProjs)
        ProjectionDialog.setTabOrder(self.listWidgetProjs, self.pushButtonDelProj)
        ProjectionDialog.setTabOrder(self.pushButtonDelProj, self.pushButtonAddProj)
        ProjectionDialog.setTabOrder(self.pushButtonAddProj, self.tableWidgetEvents)
        ProjectionDialog.setTabOrder(self.tableWidgetEvents, self.pushButtonDelEvent)
        ProjectionDialog.setTabOrder(self.pushButtonDelEvent, self.pushButtonClose)

    def retranslateUi(self, ProjectionDialog):
        ProjectionDialog.setWindowTitle(_translate("ProjectionDialog", "SSP projections", None))
        self.pushButtonClose.setText(_translate("ProjectionDialog", "Close", None))
        self.labelUsingEvents.setText(_translate("ProjectionDialog", "Using %% events for projections", None))
        self.labelStart.setText(_translate("ProjectionDialog", "Start time before event:", None))
        self.doubleSpinBoxStart.setSuffix(_translate("ProjectionDialog", "s", None))
        self.labelEnd.setText(_translate("ProjectionDialog", "End time after event", None))
        self.doubleSpinBoxEnd.setSuffix(_translate("ProjectionDialog", "s", None))
        self.pushButtonPlotEpochs.setToolTip(_translate("ProjectionDialog", "Shows the quality of the averaged artefacts on each channel.", None))
        self.pushButtonPlotEpochs.setText(_translate("ProjectionDialog", "Plot average epochs", None))
        self.labelVectors.setToolTip(_translate("ProjectionDialog", "Number of projections calculated for events. Try increasing this if the artefact is not completely removed.", None))
        self.labelVectors.setText(_translate("ProjectionDialog", "Number of projection vectors for EEG channels:", None))
        self.spinBoxVectors.setToolTip(_translate("ProjectionDialog", "Number of projections calculated for events. Try increasing this if the artefact is not completely removed.", None))
        self.pushButtonShowEvents.setToolTip(_translate("ProjectionDialog", "You can view the location of the events in relation to the actual blinks.", None))
        self.pushButtonShowEvents.setText(_translate("ProjectionDialog", "Show event locations in mne_browse_raw", None))
        self.labelProjections.setText(_translate("ProjectionDialog", "Added projection vectors", None))
        self.pushButtonDelProj.setText(_translate("ProjectionDialog", "Delete projection", None))
        self.pushButtonAddProj.setText(_translate("ProjectionDialog", "Add SSP projections", None))
        self.labelEvents.setText(_translate("ProjectionDialog", "Events", None))
        item = self.tableWidgetEvents.horizontalHeaderItem(0)
        item.setText(_translate("ProjectionDialog", "zdf<f", None))
        self.pushButtonDelEvent.setToolTip(_translate("ProjectionDialog", "Delete single event.", None))
        self.pushButtonDelEvent.setText(_translate("ProjectionDialog", "Delete event", None))

